services:
  - type: web
    name: edustat
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn edustat.wsgi:application"
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: edustat-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: edustat-db
    plan: free
