# Generated by Django 6.0.1 on 2026-01-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
    ]
