# Generated by Django 5.1.1 on 2026-06-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system_admin', 'System Administrator'), ('school_admin', 'School Administrator'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20)),
                ('school_name', models.CharField(blank=True, default='Rwanda Ministry of Education', max_length=150)),
                ('student_id_ref', models.CharField(blank=True, default='', help_text='Student record ID — required for student accounts', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
